farshore:
      app:
        options:
            redis:
              auth:
                  enabled: False
            otelcollectoringest: http://splunk-otel-collector:9943
            latency-measure: local
            test-src-locale: CN
            test-target-realm: us1
            test-metric-base-name: nike-testing-metric
            result-metric-name: nike-test-result
            sfx-api-url: https://api.us1.signalfx.com